import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dezure test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="w-full h-screen bg-gradient-to-br from-color-800 to-color-950">{children}</body>
    </html>
  );
}
